name: "Deploy Development Branch"

on:
    push:
        branches:
            - development

permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        uses: ./.github/workflows/terraform.yml
        with:
            environment: "development"
            aws-region: "sa-east-1"
            aws-assume-role-arn: "arn:aws:iam::773012663624:role/github-actions-raulpacheco2k"
            aws-s3-terraform-state-file: "raulpacheco2k-sa-east-1-terraform-state-file"
