name: "Terraform Workflow"

on:
    workflow_call:
        inputs:
            environment:
                type: string
                required: true
            aws-region:
                type: string
                required: true
            aws-assume-role-arn:
                type: string
                required: true
            aws-s3-terraform-state-file:
                type: string
                required: true
            aws-dynamodb-terraform-lock:
                type: string
                required: true

jobs:
    terraform:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash

        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4
              with:
                  terraform_version: 1.14.6

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6
              with:
                  role-to-assume: ${{ inputs.aws-assume-role-arn }}
                  role-session-name: GitHub_to_AWS_via_FederatedOIDC
                  aws-region: ${{ inputs.aws-region }}

            - name: Read Destroy Configuration
              id: read-destroy-config
              run: |
                  DESTROY="$(jq -r '.${{ inputs.environment }}' ./infrastructure/terraform/destroy.json)"
                  echo "destroy=$(echo $DESTROY)" >> $GITHUB_OUTPUT

            - name: Terraform Init
              working-directory: ./infrastructure/terraform
              run: |
                  terraform init \
                    -backend-config="bucket=${{ inputs.aws-s3-terraform-state-file }}" \
                    -backend-config="key=${{ github.event.repository.name }}" \
                    -backend-config="region=${{ inputs.aws-region }}" \
                    -backend-config="dynamodb_table=${{ inputs.aws-dynamodb-terraform-lock }}"

            - name: Terraform Validate
              working-directory: ./infrastructure/terraform
              run: terraform validate

            - name: Terraform Destroy
              working-directory: ./infrastructure/terraform
              if: steps.read-destroy-config.outputs.destroy == 'true'
              id: terraform-destroy
              run:
                  terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
                  terraform destroy -var-file="./environments/${{ inputs.environment }}/terraform.tfvars" -auto-approve

            - name: Terraform Plan
              working-directory: ./infrastructure/terraform
              if: steps.read-destroy-config.outputs.destroy != 'true'
              id: terraform-plan
              run:
                  terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
                  terraform plan -var-file="./environments/${{ inputs.environment }}/terraform.tfvars" -out="${{ inputs.environment }}.plan"

            - name: Terraform Apply
              working-directory: ./infrastructure/terraform
              if: steps.read-destroy-config.outputs.destroy != 'true'
              id: terraform-apply
              run:
                  terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
                  terraform apply "${{ inputs.environment }}.plan"
